version: "3.4"
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test123
    ports:
      - 27017:27017
  phpwlaravel:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - 82:80
      - 8181:8181
    volumes:
      - ./subscription-management:/app
    depends_on:
      - mongodb
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
volumes:
  phpwlaravel:


